# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LastCall-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LastCall-App
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'

  target 'LastCall-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LastCall-AppUITests' do
    # Pods for testing
  end

end
